#############################################################################
# Makefile for building: gpdom
# Generated by qmake (2.01a) (Qt 4.8.1) on: Fri Aug 10 15:32:12 2012
# Project:  gpdom.pro
# Template: subdirs
# Command: /usr/bin/qmake QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o Makefile gpdom.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-gnuplot-- \
		sub-gpdom-lib \
		sub-console

gnuplot++//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) gnuplot++/ || $(MKDIR) gnuplot++/ 
	cd gnuplot++/ && $(QMAKE) /home/kedrzu/Programowanie/gpdom/src/gnuplot++/gnuplot++.pro QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o $(MAKEFILE)
sub-gnuplot---qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) gnuplot++/ || $(MKDIR) gnuplot++/ 
	cd gnuplot++/ && $(QMAKE) /home/kedrzu/Programowanie/gpdom/src/gnuplot++/gnuplot++.pro QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o $(MAKEFILE)
sub-gnuplot--: gnuplot++//$(MAKEFILE) FORCE
	cd gnuplot++/ && $(MAKE) -f $(MAKEFILE)
sub-gnuplot---make_default: gnuplot++//$(MAKEFILE) FORCE
	cd gnuplot++/ && $(MAKE) -f $(MAKEFILE) 
sub-gnuplot---make_first: gnuplot++//$(MAKEFILE) FORCE
	cd gnuplot++/ && $(MAKE) -f $(MAKEFILE) first
sub-gnuplot---all: gnuplot++//$(MAKEFILE) FORCE
	cd gnuplot++/ && $(MAKE) -f $(MAKEFILE) all
sub-gnuplot---clean: gnuplot++//$(MAKEFILE) FORCE
	cd gnuplot++/ && $(MAKE) -f $(MAKEFILE) clean
sub-gnuplot---distclean: gnuplot++//$(MAKEFILE) FORCE
	cd gnuplot++/ && $(MAKE) -f $(MAKEFILE) distclean
sub-gnuplot---install_subtargets: gnuplot++//$(MAKEFILE) FORCE
	cd gnuplot++/ && $(MAKE) -f $(MAKEFILE) install
sub-gnuplot---uninstall_subtargets: gnuplot++//$(MAKEFILE) FORCE
	cd gnuplot++/ && $(MAKE) -f $(MAKEFILE) uninstall
gpdom-lib//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) gpdom-lib/ || $(MKDIR) gpdom-lib/ 
	cd gpdom-lib/ && $(QMAKE) /home/kedrzu/Programowanie/gpdom/src/gpdom-lib/gpdom-lib.pro QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o $(MAKEFILE)
sub-gpdom-lib-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) gpdom-lib/ || $(MKDIR) gpdom-lib/ 
	cd gpdom-lib/ && $(QMAKE) /home/kedrzu/Programowanie/gpdom/src/gpdom-lib/gpdom-lib.pro QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o $(MAKEFILE)
sub-gpdom-lib: gpdom-lib//$(MAKEFILE) FORCE
	cd gpdom-lib/ && $(MAKE) -f $(MAKEFILE)
sub-gpdom-lib-make_default: gpdom-lib//$(MAKEFILE) FORCE
	cd gpdom-lib/ && $(MAKE) -f $(MAKEFILE) 
sub-gpdom-lib-make_first: gpdom-lib//$(MAKEFILE) FORCE
	cd gpdom-lib/ && $(MAKE) -f $(MAKEFILE) first
sub-gpdom-lib-all: gpdom-lib//$(MAKEFILE) FORCE
	cd gpdom-lib/ && $(MAKE) -f $(MAKEFILE) all
sub-gpdom-lib-clean: gpdom-lib//$(MAKEFILE) FORCE
	cd gpdom-lib/ && $(MAKE) -f $(MAKEFILE) clean
sub-gpdom-lib-distclean: gpdom-lib//$(MAKEFILE) FORCE
	cd gpdom-lib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-gpdom-lib-install_subtargets: gpdom-lib//$(MAKEFILE) FORCE
	cd gpdom-lib/ && $(MAKE) -f $(MAKEFILE) install
sub-gpdom-lib-uninstall_subtargets: gpdom-lib//$(MAKEFILE) FORCE
	cd gpdom-lib/ && $(MAKE) -f $(MAKEFILE) uninstall
console//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) console/ || $(MKDIR) console/ 
	cd console/ && $(QMAKE) /home/kedrzu/Programowanie/gpdom/src/console/console.pro QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o $(MAKEFILE)
sub-console-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) console/ || $(MKDIR) console/ 
	cd console/ && $(QMAKE) /home/kedrzu/Programowanie/gpdom/src/console/console.pro QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o $(MAKEFILE)
sub-console: console//$(MAKEFILE) FORCE
	cd console/ && $(MAKE) -f $(MAKEFILE)
sub-console-make_default: console//$(MAKEFILE) FORCE
	cd console/ && $(MAKE) -f $(MAKEFILE) 
sub-console-make_first: console//$(MAKEFILE) FORCE
	cd console/ && $(MAKE) -f $(MAKEFILE) first
sub-console-all: console//$(MAKEFILE) FORCE
	cd console/ && $(MAKE) -f $(MAKEFILE) all
sub-console-clean: console//$(MAKEFILE) FORCE
	cd console/ && $(MAKE) -f $(MAKEFILE) clean
sub-console-distclean: console//$(MAKEFILE) FORCE
	cd console/ && $(MAKE) -f $(MAKEFILE) distclean
sub-console-install_subtargets: console//$(MAKEFILE) FORCE
	cd console/ && $(MAKE) -f $(MAKEFILE) install
sub-console-uninstall_subtargets: console//$(MAKEFILE) FORCE
	cd console/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: gpdom.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o Makefile gpdom.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o Makefile gpdom.pro

qmake_all: sub-gnuplot---qmake_all sub-gpdom-lib-qmake_all sub-console-qmake_all FORCE

make_default: sub-gnuplot---make_default sub-gpdom-lib-make_default sub-console-make_default FORCE
make_first: sub-gnuplot---make_first sub-gpdom-lib-make_first sub-console-make_first FORCE
all: sub-gnuplot---all sub-gpdom-lib-all sub-console-all FORCE
clean: sub-gnuplot---clean sub-gpdom-lib-clean sub-console-clean FORCE
distclean: sub-gnuplot---distclean sub-gpdom-lib-distclean sub-console-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-gnuplot---install_subtargets sub-gpdom-lib-install_subtargets sub-console-install_subtargets FORCE
uninstall_subtargets: sub-gnuplot---uninstall_subtargets sub-gpdom-lib-uninstall_subtargets sub-console-uninstall_subtargets FORCE

sub-gnuplot---check: gnuplot++/$(MAKEFILE)
	cd gnuplot++/ && $(MAKE) -f $(MAKEFILE) check
sub-gpdom-lib-check: gpdom-lib/$(MAKEFILE)
	cd gpdom-lib/ && $(MAKE) -f $(MAKEFILE) check
sub-console-check: console/$(MAKEFILE)
	cd console/ && $(MAKE) -f $(MAKEFILE) check
check: sub-gnuplot---check sub-gpdom-lib-check sub-console-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

